M48
; DRILL file {KiCad (6.0.5)} date Sat Dec  3 11:34:01 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-03T11:34:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.250
%
G90
G05
T1
X120.877Y-78.185
X120.877Y-135.185
X141.377Y-78.185
X141.377Y-135.185
T0
M30
